### ISSUE TITLE
Weird non-deterministic errors with postgres and jsonb in certain rare scenarios. 

### ISSUE THREAD

**Issue by reite** [haskell-beam/beam#544] opened 2021-01-24 08:20 UTC
I have a web application using beam that has been running on beam-core 0.6.0.0 and beam-postgres for almost 2 years without issue. I recently upgraded to beam-core 0.9.0.0 and started rarely getting a decodeUtf8 error on certain requests. After a lot of debugging I have narrowed it down to queries on JSONB columns in some cases will return data from different columns than those queried. I am using Postgres 12

I have been able to reproduce the errors on my database, but it only happens in very few scenarios so I am afraid it will be difficult to create a minimal example. In my database I have a JSONB column in a certain row that contains data like this (some data removed):

```
{
    "-Kw06qjdIOYmTC8StGdj": {
        "data": {
            "-Kw07GBzKMX7DwsfDfYS": {
                "fields": {
                    "invoice_no": "xxxx",
                    "invoice_curr": "xxx",
                    "invoice_amount": "xxxx"
                }
            },
            "-L25nTRq7BzgHeuRD7lT": {
                "files": [
                    {
                        "name": "Invoice xxxx.pdf",
                        "path": "xxx/xxx/Invoice xxxx.pdf"
                    }
                ]
            }
        },
        "completed": {
            "by": "VBKADPAK5SZv2wX8FBg1UBIUIUG3",
            "when": "2018-01-31T14:34:34.519Z"
        }
    },
}
```

I can query this column by running this query with beam:

```
main = do
  connection <- connectPostgreSQL "..."

  pgjsonResult <- runBeamPostgresDebug putStrLn connection $ runSelectReturningOne $ select $ do
                    entity <-  all_ (getTable1 myDatabase)
                    guard_ (getEntityId entity ==. val_ "SomeId"))
                    return $ getPgJSONBField entity 

  print pgjsonResult 
```

When I run this query I get the expected result every time. The weirdness appears when I run a second query on another table that contains PgJSONB columns:

```
main = do
  connection <- connectPostgreSQL "..."

  pgjsonResult <- runBeamPostgresDebug putStrLn connection $ runSelectReturningOne $ select $ do
                    entity <-  all_ (getTable1 myDatabase)
                    guard_ (getEntityId entity ==. val_ "SomeId"))
                    return $ getPgJSONBField entity 

  runBeamPostgresDebug putStrLn connection $ runSelectReturningOne $ select $ do
        entity2 <- all_ (getTable2 glomoSqlDb)
        guard_ (getEntity2Id entity2 ==. val_ "SomeOtherId")
        return $ entity2 

  print pgjsonResult 
```

After doing that my Json result will some times looks like this. Notice the change under the "files" field:
```
{
  "-Kw06qjdIOYmTC8StGdj": {
    "data": {
      "-L25nTRq7BzgHeuRD7lT": {
        "files": [
          {
            "tle\"": "imesheets received",
            "cond": "ns\": {\"completed\": 2}}, {\"title\": \"Invoice sent\", \"condition"
          }
        ]
      },
      "-Kw07GBzKMX7DwsfDfYS": {
        "fields": {
          "invoice_no": "xxxx",
          "invoice_amount": "xxx",
          "invoice_curr": "xxxx"
        }
      }
    },
    "completed": {
      "by": "VBKADPAK5SZv2wX8FBg1UBIUIUG3",
      "when": "2018-01-31T14:34:34.519Z"
    }
  }
}
```

This does not happen every time and the content under "files" will change to other values too randomly. I can recognize the 
 data that appears in my json from the second row queried.

Any ideas on how this is possible? Am I doing something obviously wrong? Any ideas on what I can do to debug further?

**Comment by kmicklas** [comment] 2021-01-24 15:03
To confirm I'm understanding this correctly, performing a second query after the first retroactively causes an issue with the result of the first query? If so that sounds like a laziness issue but I can't think of any place that could be happening.

To help debug, can you post the generated SQL queries, and try to confirm whether you have the same issue running them directly with `postgresql-simple`? This looks like it could be a deserialization issue, not an issue with the query. Also, are you using an up to date `postgresql-simple`?

Just a random shot in the dark, are you sure both the columns in the online schema and in your Beam table types are `jsonb` and not `json`? I'm wondering if there could be some sort of type mismatch like that.

**Comment by reite** [comment] 2021-01-25 03:15
It does indeed seem like the second query interfers with the value of the first. If i actually print the result before doing the second query then the issue does not seem to appear.

My queries generated look like this. Here I am querying a jsonb column from the first table and a jsonb column from the second. It is data from the second column that is appearing in the first:
```
SELECT "t0"."content" AS "res0" FROM "processes" AS "t0" WHERE ("t0"."id") = ('-L4BU1Auwoq97-Hj1jkM')
SELECT "t0"."milestones" AS "res0" FROM "process_templates" AS "t0" WHERE ("t0"."id") = ('-Kw06B6X8bmkwxgPwl9d')
```

When I run the same queries with just postgres simple I have not been able to reproduce the issue:
```
debugPostgresSimple = do
    connection <- connectPostgreSQL "..."

    [Only i] <- query_ connection "SELECT \"t0\".\"content\" AS \"res6\" FROM \"processes\" AS \"t0\" WHERE (\"t0\".\"id\") IN ('-L4BU1Auwoq97-Hj1jkM')"
    
    [Only (i2 :: Value)] <- query_ connection "SELECT \"t0\".\"milestones\" AS \"res0\" FROM \"process_templates\" AS \"t0\" WHERE (\"t0\".\"id\") = ('-Kw06B6X8bmkwxgPwl9d')"
    
    print (i :: Value)
    return ()
```
However here a plain Value is used instead of the (PgJSONB MyCustomType). I am starting to suspect as you say that there is a problem due to laziness and deserialization to the PgJSONB type. It is very strange that that it happens non-deterministically though. 

Both queries are querying JSONB columns. I can confirm that in my Beam model they are wrapped in PgJSONB and when I inspect the columns in pgAdmin they are of type jsonb.

**Comment by kmicklas** [comment] 2021-01-25 23:08
Can you try using `runReturningMany`? I'm wondering if this has to do with the non-streaming implementation introduced in #520.

**Comment by reite** [comment] 2021-01-26 03:37
I tried with ```runReturningMany``` and the issue does indeed disappear.

**Comment by kmicklas** [comment] 2021-01-27 00:01
@reite Since I don't have an easy way to reproduce this myself, do you mind trying your case patching beam-postgres to remove the [call to `Pg.unsafeFreeResult`](https://github.com/haskell-beam/beam/blob/4d30ed45b16c41be26cb6301e9033c99379bf2d9/beam-postgres/Database/Beam/Postgres/Connection.hs#L232)?

**Comment by reite** [comment] 2021-01-27 02:49
I just tried that and it also resolved the issue.

I forked beam here and added a commit removing the call:
https://github.com/reite/beam

Then in my stack I commented out beam and used the git version:
```
#- beam-core-0.9.0.0@sha256:e5b1cb4d5b8a8a166f3373e8718672a3884feb9a5a133404b047b0af76538023,5282
#- beam-migrate-0.5.0.0@sha256:d3f7e333ec9e96122ccec6be0d38a88f766dfc248323be73fd0b3cee245ea421,4923
#- beam-postgres-0.5.0.0@sha256:3008f802b25fffaee2edf7f8f840a073ee630049031cda0b4ea7912b6656c813,4333
- git: https://github.com/reite/beam.git
  commit: 723cb308e11931cd89031cc73abb2994c9264a7e
  subdirs:
    - beam-core
    - beam-migrate
    - beam-postgres
```
I cannot see any other commit since the 0.9.0.0 release that would affect my issue, but if you would prefer I try from another commit than the latest, let me know which one.

**Comment by kmicklas** [comment] 2021-01-28 00:27
@reite Can you also try to reproduce with this patch: #546? I've been trying to set up a test to reproduce this but have been unsuccessful so far, unfortunately.

**Comment by reite** [comment] 2021-01-28 03:25
I tried your patch and it also solved the issue.

I have noticed that both the data being replaced and the data replacing it is the contents of lists (Haskell lists or Aeson Arrays). I believe that all the other fields in an aeson Value structure is strict so there might be some connection there. My PgJSONB values are nested haskell records that also contains nested json values.

**Comment by kmicklas** [comment] 2021-02-11 00:06
Closing this although I've unfortunately not been able to produce a test to verify that #546 fixes it. I'll try to get out a bug fix release shortly.

**Closed by kmicklas** 2021-02-11 00:06 UTC
Labels: bug, critical

**Comment by ondrap** [comment] 2021-06-23 21:09
I can get the error here quite deterministically: https://github.com/ondrap/beam-sql-bug

It would be nice to release a new version :)
