### ISSUE TITLE
hackage release dependency restriction

### ISSUE THREAD

**Issue by rsoeldner** [haskell-beam/beam#455] opened 2020-04-29 12:38 UTC
Hi,

can we update the hackage release with the more relaxed boundaries (hackage dependent-map (==0.2.*), repo < 0.4 )

https://github.com/tathougies/beam/blob/master/beam-migrate/beam-migrate.cabal#L82

**Comment by kmicklas** [comment] 2020-06-08 12:39
Closing as duplicate of #460.

**Closed by kmicklas** 2020-06-08 12:39 UTC
