### ISSUE TITLE
Link to manual broken 

### ISSUE THREAD

**Issue by Profpatsch** [haskell-beam/beam#523] opened 2020-09-25 14:34 UTC
Both in the hackage description

> For more information, see the user manual and tutorial on [GitHub pages](https://tathougies.github.io/beam).

as well as the module documentation

> Most users will want to consult [the manual](https://tathougies.github.io/beam).

**Comment by kmicklas** [comment] 2020-09-25 22:58
Closing this as a duplicate of #489, among others. The links are updated on master, we just need to release to Hackage. (Hopefully very soon!)

**Closed by kmicklas** 2020-09-25 22:58 UTC
