### ISSUE TITLE
verifySchema and "TODO: array migrations"

### ISSUE THREAD

**Issue by GulinSS** [haskell-beam/beam#598] opened 2021-10-17 15:18 UTC
Recently I was needed to change my schema to define a column with sql array type of text. I am using `verifySchema` at app start to make sure that all migrations had been executed properly and my database schema meets expectations of my haskell beam code. But I faced with error `TODO: array migrations` from

https://github.com/haskell-beam/beam/blob/294c6fe4dbbdbc23e47f4b2a8b0114c8dc8975ce/beam-postgres/Database/Beam/Postgres/Syntax.hs#L570

Are there any workarounds or tricks to continue usage of verified schema? Or may be it is not a big deal to help with implementation of array migrations? Please let me know.

**Comment by kmicklas** [comment] 2021-11-08 13:54
Closing as duplicate of #354. If you're feeling adventurous, PRs to support this would be much appreciated!

**Closed by kmicklas** 2021-11-08 13:54 UTC
