### ISSUE TITLE
beam-postgres error: "libsqlite3.so.0: symbol close version GLIBC_2.2.5..."

### ISSUE THREAD

**Issue by NeoLight1010** [haskell-beam/beam#631] opened 2022-02-04 02:07 UTC
I'm tyring to use beam-postgres in my Stack app, but when I add it to the dependencies, an error is shown by HLS:

```
/lib/x86_64-linux-gnu/libsqlite3.so.0: symbol close version GLIBC_2.2.5 not defined in file libpthread.so.0 with link time reference
```
![image](https://user-images.githubusercontent.com/58057324/152467142-9ab3a7f6-08a9-40ef-afce-55d0b897341d.png)

When running `stack build`, the project is built successfully, although I haven't written any `beam` stuff yet.

### Info
- **Stack snapshot:** nightly-2022-02-01
- **OS:** Pop_OS! 21.10

### package.yaml dependencies section

```yaml
dependencies:
- base >= 4.7 && < 5
- beam-core
- beam-postgres
- blaze-html
- containers
- http-types
- scotty
- text
```

**Comment by kmicklas** [comment] 2022-02-04 03:13
Are you using just Postgres or SQLite too? Just double checking because the error mentions SQLite while the description says Postgres.

Can you build directly with stack? This would help eliminate the possibility that the issue is with HLS.

**Comment by NeoLight1010** [comment] 2022-02-04 03:30
> Are you using just Postgres or SQLite too? Just double checking because the error mentions SQLite while the description says Postgres.
> 
> Can you build directly with stack? This would help eliminate the possibility that the issue is with HLS.

I'm using `beam-postgres`. I am confused why it says SQLite too.

And yes, the project builds successfully using stack, but I haven't tried writting any code with Beam yet. I've updated the issue with a bit more info.

**Comment by kmicklas** [comment] 2022-02-04 12:26
In that case, this sounds like an issue with HLS or your distro. I'm going to close this here since I don't believe there's anything Beam can do about this.

**Closed by kmicklas** 2022-02-04 12:26 UTC
